### ISSUE TITLE
Don't continue on Error : use "set -eux"

### ISSUE THREAD

**Issue by dharmeshkakadia** [hdinsight/drill-hdinsight#1]
We should use "set -e" at the start of the script which will prevent further command execution. This would help in failing fast. It would be actually even better to use "set -eux" which will also help in debugging and enforces good standards.

**Comment by yaron2** [comment]
Agree @dharmeshkakadia .. see commit https://github.com/hdinsight/drill-hdinsight/commit/9080922a8349ea0d91beb1eae02d7d005537004c

**Comment by dharmeshkakadia** [comment]
Thanks. Can you please do Pull Requests first, from next time :)
